master
huji-nlp/ucca pull request #35
Opened 2018-10-08 11:06 UTC by shachardon

when splitting token with currency sign, tag it as unanalyzable 
(and not punctuation).
split tokens with apostrophe or hyphen according to an instruction file.

2018-10-08 12:35 UTC, danielhers requested changes
Looks good, but please see comments.

2018-10-08 12:35 UTC, danielhers commented on scripts/fix_tokenization.py
> +    pretermoinal_parent = Element(SiteCfg.Tags.Unit,
typo: should be `preterminal_parent`

2018-10-08 12:35 UTC, danielhers commented on scripts/fix_tokenization.py
> +             tokens[1].replace(',', '')):
What is the condition with the comma for? Shouldn't it also be with `isdigit`?

2018-10-08 12:35 UTC, danielhers commented on scripts/fix_tokenization.py
> +                                                           False))
I think it's better to write `is_punct=False` instead of just `False` for clarity. Same for the similar cases below.

2018-10-09 05:44 UTC, shachardon commented
Yes, it was supposed to be isdigit(),  I missed it when I did the merge.
Fixed all the comments.

‫בתאריך יום ב׳, 8 באוק׳ 2018 ב-15:35 מאת ‪Daniel Hershcovich‬‏ <‪
notifications@github.com‬‏>:‬

> *@danielhers* requested changes on this pull request.
>
> Looks good, but please see comments.
> ------------------------------
>
> In scripts/fix_tokenization.py
> <https://github.com/danielhers/ucca/pull/35#discussion_r223340186>:
>
> > @@ -42,6 +55,23 @@ def get_id(self):
>          return ret
>
>
> +def create_unit_element(state, text, tag):
> +    elem = Element(SiteCfg.Tags.Terminal,
> +                   {SiteCfg.Attr.SiteID: state.get_id()})
> +    elem.text = text
> +    preterminal_elem = Element(SiteCfg.Tags.Unit,
> +                               {SiteCfg.Attr.SiteID: state.get_id()})
> +    pretermoinal_parent = Element(SiteCfg.Tags.Unit,
>
> typo: should be preterminal_parent
> ------------------------------
>
> In scripts/fix_tokenization.py
> <https://github.com/danielhers/ucca/pull/35#discussion_r223340469>:
>
> > @@ -72,6 +102,23 @@ def insert_retokenized(terminal, preterminal_parent, tokens, index_in_pretermina
>      insert_punct(insert_index + 1, preterminal_parent, state, tokens[non_punct_index + 1:])
>
>
> +def insert_retokenized_currency(i, terminals, preterminals,
> +                                preterminal_parents,
> +                                tokens, state):
> +    if len(tokens) == 2 and tokens[0] in CURRENCIES and \
> +            (tokens[1].replace('.', '', 1).isdigit() or
> +             tokens[1].replace(',', '')):
>
> What is the condition with the comma for? Shouldn't it also be with
> isdigit?
> ------------------------------
>
> In scripts/fix_tokenization.py
> <https://github.com/danielhers/ucca/pull/35#discussion_r223340865>:
>
> > @@ -72,6 +102,23 @@ def insert_retokenized(terminal, preterminal_parent, tokens, index_in_pretermina
>      insert_punct(insert_index + 1, preterminal_parent, state, tokens[non_punct_index + 1:])
>
>
> +def insert_retokenized_currency(i, terminals, preterminals,
> +                                preterminal_parents,
> +                                tokens, state):
> +    if len(tokens) == 2 and tokens[0] in CURRENCIES and \
> +            (tokens[1].replace('.', '', 1).isdigit() or
> +             tokens[1].replace(',', '')):
> +        terminals[i].text = tokens[1]
> +        index_to_insert = preterminal_parents[i].getchildren(). \
> +            index(preterminals[i])
> +        preterminal_parents[i].insert(index_to_insert,
> +                                      create_token_element(state,
> +                                                           tokens[0],
> +                                                           False))
>
> I think it's better to write is_punct=False instead of just False for
> clarity. Same for the similar cases below.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/danielhers/ucca/pull/35#pullrequestreview-162440523>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AoKGktz95cwoysvNqcP26fBjcUodDxqJks5ui0Z3gaJpZM4XMtW4>
> .
>

2018-10-11 07:45 UTC, merged