Multiple categories
huji-nlp/ucca pull request #56
Opened 2019-01-14 20:54 UTC by adishalev

UCCA now supports: 
1. annotations with more than one category per edge.
2. annotations from refinement tasks

* back-supporting old xml format

2019-01-15 09:48 UTC, danielhers requested changes
Thanks, this is an important change. Please see my comments. Also, I'd like to have the tests pass before merging: https://travis-ci.org/danielhers/ucca/jobs/479585327 (you can run them offline with pytest: `pytest ucca/tests`).

2019-01-15 09:48 UTC, danielhers commented on ucca/convert.py
> +            categories[c['id']] = {'name': c["name"], 'parent': c['parent'] if 'parent' in c else None, 'layer': base_layer}
`c['parent'] if 'parent' in c else None` can be replaced by `c.get("parent")`

2019-01-15 09:48 UTC, danielhers commented on ucca/convert.py
> +            c_slot = category["slot"] if 'slot' in category else ""
`category["slot"] if 'slot' in category else ""` can be replaced by `category.get("slot", "")`

2019-01-15 09:48 UTC, danielhers commented on ucca/convert.py
> +            c_layer = categories[category["id"]]['layer']
Better extract `categories[category["id"]]` to a variable

2019-01-15 09:48 UTC, danielhers commented on ucca/convert.py
> +                c_parent = c_parent['name']
Shouldn't the parent category name be mapped to an edge tag too?

2019-01-15 09:48 UTC, danielhers commented on ucca/convert.py
> +            unit_categories.append((c_tag, c_slot, c_layer, c_parent))
Why not create `Category` objects rather than dealing with 4-tuples everywhere?

2019-01-15 09:48 UTC, danielhers commented on ucca/core.py
> +    the connection type between the Nodes. an edge can have multiple annotations, representing
Capitalization

2019-01-15 09:48 UTC, danielhers commented on ucca/core.py
> +    def categories(self, new_categories):
Since it's a setter, I would expect it to *replace* the list of categories rather than adding to it

2019-01-15 09:48 UTC, danielhers commented on ucca/core.py
> +        for category in self._categories:
Can be replaced by `yield from self._categories`.

2019-01-15 09:48 UTC, danielhers commented on ucca/core.py
> +        """Iterates the :class:`Edge` objects in the subtree of self.
"subtree" isn't correct here

2019-01-15 09:48 UTC, danielhers commented on ucca/core.py
> +        :param obj: yield Category objects
There is no such param in this method

2019-01-15 09:48 UTC, danielhers commented on ucca/core.py
> +            a :class:`Node` or :class:`Edge` object according to the iteration
Should be Category objects

2019-01-15 09:48 UTC, danielhers commented on ucca/core.py
> +        :param edge_categories: the labels of the :class:`Edge` connecting between the
Need more informative documentation on the expected type of the list elements (4-tuples) if we keep it this way

2019-01-15 09:48 UTC, danielhers commented on ucca/core.py
> -    def __init__(self, root, tag, parent, child, attrib=None):
How about optionally allowing the `tag` parameter as a shortcut for adding a single category?

2019-01-15 09:48 UTC, danielhers commented on ucca/core.py
> +        return self._categories
I think this and `refined_categories` should copy the attributes (by calling `dict()` and `list()` respectively), like the other getters

2019-01-15 09:48 UTC, danielhers commented on ucca/core.py
> +        self._categories[category.tag] = {"layer": category.layer, "slot": category.slot, "parent": category.parent}
Why a dict and not Category object?

2019-01-15 09:48 UTC, danielhers commented on ucca/layer1.py
> +        :param edge_categories: list of categories on the Edge between the parent and the new FNode.
Again, document the exact expected format of the parameter (tuples or Category objects)

2019-01-15 09:48 UTC, danielhers commented on ucca/convert.py
> +            node.add([(EdgeTags.Terminal, base_slot, base_layer, "")], terminal)
`""` for parent can be omitted since it's optional (same for other places in the code)

2019-01-15 09:48 UTC, danielhers commented on ucca/normalization.py
> +        scene = l1.add_fnode(node, [(ETags.ParallelScene)])
Redundant parentheses - if you want a 1-tuple, you must add a comma: `(ETags.ParallelScene,)`. Same for other places in the code

2019-01-15 09:48 UTC, danielhers commented on uccaapp/export_units_by_filter.py
> +                all_tags = []
This is fine, but FYI, you could write it as `all_tags = [c.tag for edge in node for c in edge.categories]`

2019-01-15 14:31 UTC, danielhers commented
@adishalev let me know if you need help with the fixes (to the tests etc.).

2019-01-19 19:53 UTC, danielhers commented
Looks good, I think. Just need to update `test_files/standard3.xml` to be in the new format.

2019-01-19 19:55 UTC, danielhers commented on ucca/core.py
> +    #    self._categories[0].tag = new_tag
Is this commented-out on purpose?

2019-01-19 19:58 UTC, adishalev commented on ucca/core.py
> +    #    self._categories[0].tag = new_tag
you can remove it

2019-01-19 19:58 UTC, adishalev commented
I changed the code to support adding an edge with a single tag by moving the code that handles multiple categories to core.Node.add_multiple() and layer1.Fnode.add_fnode_multiple(). it fixed most of the test failures.

All the tests pass now, except for test_to_standard() which fails because the xml that was loaded from site has &quot; while the loaded ref has "" in the extra remarks.
<extra remarks="&quot;remark&quot;"
<extra remarks="remark"
I'm not sure which one is correct, could you please take a look at this?

2019-01-19 20:05 UTC, adishalev commented
It's ok to leave test_files/standard3.xml as is, it is converted to the new format as part of the test.

2019-01-20 05:46 UTC, danielhers commented
Looks like `from_standard` strips the quotes. It didn't fail before because it just wasn't called in the test.
It strips the quotes because it tries to read the `extra` entries as JSON, and if it succeeds, it returns the decoded JSON. Otherwise it returns the original string. Just `remarks` is not valid JSON, but `"remarks"` is, and is decoded to the string `remarks`... I'd like to keep this JSON decoding capability (since sometimes we save actual dicts of values to `extra` entries), so I think I'll just remove the extra `&quot;`s from `standard3.xml`.

2019-01-20 05:58 UTC, merged

2019-01-20 06:06 UTC, danielhers commented
Thanks @adishalev ! I respect your choice to keep values "primitive" and create `Category` objects only internally, but I wonder what the considerations were.
By the way, I think you should configure your email with `git config --global user.email`, because right now the commits are not associated with your GitHub username.

2019-01-20 11:40 UTC, adishalev commented
I left the comments about primitives vs. categories open as I plan to change those primitives to categories as part of my next commits. 
Thanks for your tip about the git email configuration!

2019-01-20 11:46 UTC, danielhers commented
I see. It seemed pretty good already though so I merged it, but I'll be glad to merge another pull request when you're ready.