add function to check if is implicit
huji-nlp/ucca pull request #83
Opened 2019-11-22 15:00 UTC by ruixiangcui

I also added three files with implicit arguments from EWT to test _files.

2019-11-25 08:55 UTC, danielhers commented
Needs fixing: expected results in tests (ucca/tests/test_evaluation.py): https://travis-ci.org/danielhers/ucca/jobs/615591438
Implicit units used to be excluded from evaluation, but now they're included in the primary score. The expected scores should therefore be updated to account for that.

2019-11-25 08:57 UTC, danielhers commented
Also, expected results for evaluation should be added for the three new files (`implicit1.xml`, `implicit2.xml`, `implicit3.xml`) in https://github.com/danielhers/ucca/blob/master/ucca/tests/test_evaluation.py#L310

2019-11-25 08:58 UTC, danielhers requested changes

2019-11-25 08:58 UTC, danielhers commented on ucca/constructions.py
> +        self._terminal_yield_no_punct = positions(self.edge.parent.get_terminals(punct=False)) if self.is_implicit\
Good. Just had an idea: it can be rewritten `positions((self.edge.parent if self.is_implicit else self.edge.child).get_terminals(punct=False))`

2019-11-25 08:58 UTC, danielhers commented on ucca/constructions.py
> +    Categories()
What about adding an "implicit" construction? I thought you added that.

2019-11-25 08:58 UTC, danielhers commented on ucca/layer0.py
> -
Avoid changes to files if they're only whitespace

2019-11-27 15:00 UTC, ruixiangcui commented
I have modified results in tests (ucca/tests/test_evaluation.py) for passage1-passage2, simple1-simple2, and function1-function2. However, I can not find where to change result for create13-create23. 

> Needs fixing: expected results in tests (ucca/tests/test_evaluation.py): https://travis-ci.org/danielhers/ucca/jobs/615591438
> Implicit units used to be excluded from evaluation, but now they're included in the primary score. The expected scores should therefore be updated to account for that.

2019-11-27 15:28 UTC, ruixiangcui commented
At first I thought the previous test files did not have implicit arguments so I added 3 xmls. Now that I know they do have, is it still necessary to add some more test xmls to it?

2019-11-27 19:33 UTC, ruixiangcui commented
Sorry that I committed so many times. Now I have generally commanded how to use Git. 
This time I added implicit edges into Constructions; Added two test files with implicit arguments; modified test parameters (changed values and added implicit features) for  passage1-passage2, simple1-simple2, function1-function2, 120_parsed-standard3, and implicit1-implicit1_ref, implicit2-implicit2. 
Thanks for checking them!

2019-11-29 15:15 UTC, danielhers approved these changes

2019-11-29 15:15 UTC, merged